VERSION: 1.0.0
Connection:
  Hostname: irc.rizon.net
  Port: '+6697'
  Nick: EliteBot
  Ident: EliteBot
  Name: EliteBot
  BindHost: 0.0.0.0
SASL:
  UseSASL: false
  SASLNick: EliteBot
  SASLPassword: password
Logging:
  Console: true
Database:
  ConnectionString: mysql://user:password@host:port/database
